### PR TITLE
TypeScript Types

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
Following on from #11 I ended up putting the type definition together anyway. Easier than expected, and I've tested that it works correctly locally.

### CODE REVIEW

**Comment by phated** [comment]
@demurgos  can you review these?

**Review by demurgos — APPROVED** [review]
Sorry for the long delay, I had less free time at the start of the year.

These type definitions are very good: they are correct, include doc comments and use ES style.

The overloads may be simplified to match Node's `console.log` but this is minor and I won't block for this.
```typescript
// Node's `console.log` signature:
interface Console {
  log(message?: any, ...optionalParams: any[]): void;
  // ...
}
```

Thank you for your submission. :+1:

**Comment by Silic0nS0ldier** [comment]
Thought process with the overloads being the way they are was to highlight that string interpolation requires a string to achieve anything, that is unless I've misunderstood the docs.

**Comment by Silic0nS0ldier** [comment]
@phated Assuming this has just gone unnoticed, but is there anything more I need to do here?

**Comment by phated** [comment]
Definitely missed (pandemic and all). I will add this to our v5 project board.

**Review by phated — APPROVED** [review]
This looks good to me! Let's merge it and get it included in the next release 🎉 

Thanks @Silic0nS0ldier for the help and sorry for the delay!

**Pull request merged**
